name: man-lift
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.2
  - numpy=1.23.1
  - fenics-dolfin=2019.1.0
  - python=3.9
  - multiprocess=0.70.13
  - scipy=1.8.1
  - arviz=0.12.1
  - jax=0.3.15
  - scikit-sparse=0.4.6
  - sympy=1.10.1
  - pip=22.2
  - pip:
    - mici>=0.2
    - symnum>=0.1.2
    - git+https://github.com/thiery-lab/manifold_lifting@v0.1.0#egg=mlift
